# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - website

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.0.100"
  - script: dotnet build --configuration $(buildConfiguration)
    workingDirectory: website/src/LinkDotNet.Blog.Web
    displayName: "dotnet build $(buildConfiguration)"

  - script: dotnet publish -c $(buildConfiguration) --self-contained true -r win-x86
    workingDirectory: website/src/LinkDotNet.Blog.Web
    displayName: "dotnet build $(buildConfiguration)"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "website/src/LinkDotNet.Blog.Web/bin/Release/net8.0/win-x86/publish"
      includeRootFolder: false
      archiveType: zip
      archiveFile: "$(Build.ArtifactStagingDirectory)/blog/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "backend zip files"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/blog"
      ArtifactName: "blog"
    displayName: "blog publish to pipeline"
